[12.0] Added migrated code from v11 to v12.
JayVora-SerpentCS/fleet_management pull request #6
Opened 2018-12-31 12:34 UTC by nikeshscs

Hello sir,
here i send pull request of fleet_management modules from v11 to v12. 
Thank you.

2019-01-01 08:11 UTC, JayVora-SerpentCS requested changes

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_extended.py
> +    front_tire_size = fields.Float(string='Size ')
no extra space

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_extended.py
> +                                          string='Odometer Unit ',
no extra space

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_extended.py
> +                                               string='Attachments ')
no extra space

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_extended.py
> +    vehical_color_id = fields.Many2one('color.color', string='Color ')
no extra space

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_extended.py
> +    location_id = fields.Many2one('vehicle.location', string=' Location ')
no extra space

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on fleet_operations/models/fleet_service.py
> +    _inherit = 'fleet.vehicle.log.services'
def copy(self, default=None):
         if not default:
             default = {}
         raise Warning(_('You can\'t duplicate record!'))
return super(ServiceCategory, self).copy(default=default)

>>> raise pa6i return?? na jaamyu

2019-01-01 08:11 UTC, JayVora-SerpentCS commented on oca_dependencies.txt
> +ow_account_budget
mention the module names in depends manifest too

2019-01-01 10:42 UTC, nikeshscs commented
Hello @JayVora-SerpentCS,
We improved code as per requested changes.
Thank you.

2019-01-02 06:51 UTC, JayVora-SerpentCS commented
@YogendrasinhChavda please review

2019-01-02 08:55 UTC, YogendrasinhChavda commented on fleet_operations/models/fleet_extended.py
> +    front_tire_size = fields.Float(string='Size ')
@JayVora-SerpentCS Done.

2019-01-02 08:58 UTC, YogendrasinhChavda commented
@JayVora-SerpentCS 
Changes are reviewed.

2019-01-22 06:14 UTC, merged